# Site settings
title:  skorzinetzki.github.io - blog
author: Steve Korzinetzki
email:  steve.korzinetzki@lise.de
description: > 
  my personal blog about software development, 
  continuous delivery, photography and more
baseurl: ""
url: "https://skorzinetzki.github.io"
twitter_username: skorzinetzki
github_username:  skorzinetzki
500px_username:   steve-korzinetzki

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
